tmp

diff --git a/.github/workflows/nix-setup/action.yaml b/.github/workflows/nix-setup/action.yaml
--- a/.github/workflows/nix-setup/action.yaml
+++ b/.github/workflows/nix-setup/action.yaml
@@ -41,6 +41,16 @@ runs:
 
         python -c "import sys; print(sys.platform)"
 
+        model=selfdrive/modeld/models/driving_policy.onnx
+        [[ -f $model ]] || {
+          echo "model $model not found"
+          exit 1
+        }
+        if head -1 $model | grep -q git-lfs; then
+          echo "model $model is an lfs pointer"
+          exit 1
+        fi
+
     # - uses: cachix/install-nix-action@v31
     #   with:
     #     extra_nix_config: |
